// export const STUDENT_COHORT_REQUEST = "STUDENT_COHORT_REQUEST"
// export const STUDENT_COHORT_SUCCESS = "STUDENT_COHORT_SUCCESS"
// export const STUDENT_COHORT_FAIL = "STUDENT_COHORT_FAIL"
export const STUDENT_RESET = "STUDENT_RESET"

export const STUDENT_COURSES_REQUEST = "STUDENT_COURSES_REQUEST"
export const STUDENT_COURSES_SUCCESS = "STUDENT_COURSES_SUCCESS"
export const STUDENT_COURSES_FAIL = "STUDENT_COURSES_FAIL"

export const STUDENT_SESSIONS_REQUEST = "STUDENT_SESSIONS_REQUEST"
export const STUDENT_SESSIONS_SUCCESS = "STUDENT_SESSIONS_SUCCESS"
export const STUDENT_SESSIONS_FAIL = "STUDENT_SESSIONS_FAIL"

export const STUDENT_SESSION_SECTIONS_REQUEST = "STUDENT_SESSION_SECTIONS_REQUEST"
export const STUDENT_SESSION_SECTIONS_SUCCESS = "STUDENT_SESSION_SECTIONS_SUCCESS"
export const STUDENT_SESSION_SECTIONS_FAIL = "STUDENT_SESSION_SECTIONS_FAIL"

export const STUDENT_ASSESSMENTS_REQUEST = "STUDENT_ASSESSMENTS_REQUEST"
export const STUDENT_ASSESSMENTS_SUCCESS = "STUDENT_ASSESSMENTS_SUCCESS"
export const STUDENT_ASSESSMENTS_FAIL = "STUDENT_ASSESSMENTS_FAIL"